/* global window */

// ───────────────────────────────────────────────────────────
// メニュー（指定どおり: 牛乳・パンケーキ・プリン・ラスク・ジェラート）
// ───────────────────────────────────────────────────────────
const MENU = [
  {
    id: "milk",
    nameJa: "牛乳",
    nameEn: "Fresh Milk",
    subJa: "瓶詰め・冷",
    subEn: "Bottled, Cold",
    tickets: 1,
    swatch: "#F4F1EA",
  },
  {
    id: "pancake",
    nameJa: "パンケーキ",
    nameEn: "Pancake",
    subJa: "発酵バター添え",
    subEn: "With cultured butter",
    tickets: 3,
    swatch: "#F1E8D8",
  },
  {
    id: "pudding",
    nameJa: "プリン",
    nameEn: "Pudding",
    subJa: "瓶入り・濃厚",
    subEn: "Jarred, rich",
    tickets: 2,
    swatch: "#F6E9C9",
  },
  {
    id: "rusk",
    nameJa: "ラスク",
    nameEn: "Rusk",
    subJa: "薄焼き・5枚",
    subEn: "Thin, 5 pcs",
    tickets: 2,
    swatch: "#EFE3CD",
  },
  {
    id: "gelato",
    nameJa: "ジェラート",
    nameEn: "Gelato",
    subJa: "本日のフレーバー",
    subEn: "Today's flavor",
    tickets: 2,
    swatch: "#EFEFEF",
  },
];

const MENU_MAP = Object.fromEntries(MENU.map((m) => [m.id, m]));

// ───────────────────────────────────────────────────────────
// i18n
// ───────────────────────────────────────────────────────────
const STRINGS = {
  ja: {
    brand: "MILK STAND",
    brandSub: "Voice Order System",
    welcome: "いらっしゃいませ。",
    welcomeSub: "話しかけて、ご注文ください。",
    tapStart: "画面をタップ、または「注文します」と話しかけてください",
    listening: "お聞きしています",
    listeningSub: "ご注文をどうぞ",
    parsing: "確認しています",
    confirm: "ご注文内容",
    confirmSub: "内容に間違いはございませんか？",
    products: "商品一覧",
    productsSub: "タップしても注文できます",
    cart: "お会計",
    cartSub: "チケットでお支払いいただきます",
    ticket: "チケット",
    ticketSymbol: "◈",
    ticketHint: "事前購入したチケットでお支払いいただきます",
    confirmPay: "チケットで支払う",
    ticketBalance: "お手持ちチケット",
    history: "本日の注文履歴",
    historySub: "Today's orders",
    addCart: "カートに入れる",
    backHome: "ホームに戻る",
    voiceOrder: "音声で注文",
    manualOrder: "手動で選ぶ",
    proceedPay: "お会計へ進む",
    payNow: "チケットで支払う",
    cancel: "取り消す",
    back: "もどる",
    keep: "続ける",
    qty: "数量",
    subtotal: "小計",
    tax: "消費税",
    total: "合計",
    yen: "◈",
    tickets: "件",
    waiting: "受付中",
    ready: "ご用意中",
    done: "お渡し済",
    paid: "お支払い済",
    item: "点",
    listenAgain: "もう一度",
    yes: "はい",
    no: "いいえ",
    paymentCash: "現金",
    paymentCard: "クレジット",
    paymentQR: "QR決済",
    paymentIC: "交通系IC",
    examplePrompt: "例：「牛乳を2本と、プリンをひとつ」",
    transcriptHint: "認識中…",
    thankYou: "ありがとうございました",
    thankYouSub: "またのお越しをお待ちしております",
    orderNo: "注文番号",
    now: "ただいま",
    minAgo: "分前",
    settings: "設定",
    nav: { home: "ホーム", products: "商品", history: "履歴" },
  },
  en: {
    brand: "MILK STAND",
    brandSub: "Voice Order System",
    welcome: "Welcome.",
    welcomeSub: "Speak to place your order.",
    tapStart: 'Tap the screen, or say "I’d like to order"',
    listening: "Listening",
    listeningSub: "Please go ahead",
    parsing: "Confirming",
    confirm: "Your Order",
    confirmSub: "Is everything correct?",
    products: "Menu",
    productsSub: "You can also tap to order",
    cart: "Checkout",
    cartSub: "Paid with tickets",
    ticket: "Ticket",
    ticketSymbol: "◈",
    ticketHint: "Use the tickets you purchased in advance",
    confirmPay: "Pay with tickets",
    ticketBalance: "Your balance",
    history: "Today’s Orders",
    historySub: "本日の注文履歴",
    addCart: "Add to cart",
    backHome: "Back to home",
    voiceOrder: "Order by voice",
    manualOrder: "Pick manually",
    proceedPay: "Proceed to pay",
    payNow: "Pay with tickets",
    cancel: "Cancel",
    back: "Back",
    keep: "Keep",
    qty: "Qty",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    yen: "◈",
    tickets: "items",
    waiting: "In queue",
    ready: "Preparing",
    done: "Served",
    paid: "Paid",
    item: "items",
    listenAgain: "Again",
    yes: "Yes",
    no: "No",
    paymentCash: "Cash",
    paymentCard: "Card",
    paymentQR: "QR Pay",
    paymentIC: "Transit IC",
    examplePrompt: 'e.g. "Two milks and one pudding, please."',
    transcriptHint: "recognizing…",
    thankYou: "Thank you very much",
    thankYouSub: "We look forward to serving you again",
    orderNo: "Order",
    now: "just now",
    minAgo: "min ago",
    settings: "Settings",
    nav: { home: "Home", products: "Menu", history: "History" },
  },
};

// ───────────────────────────────────────────────────────────
// サンプル履歴（プロトタイプ用）
// ───────────────────────────────────────────────────────────
const SAMPLE_HISTORY = [
  {
    id: "0142",
    minAgo: 2,
    items: [
      { id: "milk", qty: 2 },
      { id: "pudding", qty: 1 },
    ],
    status: "ready",
  },
  {
    id: "0141",
    minAgo: 6,
    items: [
      { id: "pancake", qty: 1 },
      { id: "gelato", qty: 1 },
    ],
    status: "done",
  },
  {
    id: "0140",
    minAgo: 11,
    items: [
      { id: "rusk", qty: 2 },
      { id: "milk", qty: 1 },
    ],
    status: "done",
  },
  {
    id: "0139",
    minAgo: 18,
    items: [
      { id: "gelato", qty: 2 },
    ],
    status: "done",
  },
  {
    id: "0138",
    minAgo: 24,
    items: [
      { id: "pancake", qty: 2 },
      { id: "milk", qty: 1 },
    ],
    status: "done",
  },
];

window.MENU = MENU;
window.MENU_MAP = MENU_MAP;
window.STRINGS = STRINGS;
window.SAMPLE_HISTORY = SAMPLE_HISTORY;
